services:
  db:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: ilyapatis24/counter:v1.0.0
    environment:
      - PORT=3001
      - REDIS_URL=redis://db
    ports:
      - 3001
    depends_on:
      - db        
  books:
    image: ilyapatis24/books:v1.0.0
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
    ports:
      - 80:3000
    depends_on:
      - counter